platform:ios, '7.0'
pod 'AFNetworking', '~> 2.0.2'
pod 'TBMacros', '~> 0.2'
pod 'NVSlideMenuController', '~> 1.5.6'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.0.2'
pod 'SSKeychain', '~> 1.2.1'
pod 'BDBOAuth1Manager', '~> 1.0.2'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MBProgressHUD', '~> 0.8'
pod 'TTTAttributedLabel', '~> 1.8.0'
