platform:ios, '7.0'
pod 'AFNetworking', '~> 2.5.0'
pod 'TBMacros', '~> 0.2'
pod 'NVSlideMenuController'
pod 'SSKeychain'
pod 'BDBOAuth1Manager', '~> 1.5.0'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'MBProgressHUD'
pod 'TTTAttributedLabel'
pod 'GoogleAnalytics', '~> 3.13'
pod 'OAStackView', '~> 0.1.0'
pod 'ActionSheetPicker-3.0', '~> 2.0.4'
pod 'TSMessages', '~> 0.9'
pod 'Fabric'
pod 'Crashlytics'
